kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: kafka
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 8080