apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-0
  ports:
    - name: prometheus
      port: 9090
