apiVersion: v1
kind: Service
metadata:
  name: kafka-bootstrap
  namespace: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - port: 9092
      name: external
      nodePort: 32500
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-0
  namespace: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
    - port: 9092
      name: external
      nodePort: 32000
    - port: 19000
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  ports:
    - port: 9092
      name: external
      nodePort: 32001
    - port: 19000
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2
  namespace: kafka
  labels:
    app: kafka
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  ports:
    - port: 9092
      name: external
      nodePort: 32002
    - port: 19000
      name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9093
      name: internal
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9094
      name: cluster
    - port: 9095
      name: controller
